#-------------------------------
# General Site Settings
title: SEOHYUN PORTFOLIO
description: Zolan is modern minimal theme for Jekyll


#-------------------------------
# Author Settings
author:
  name: Kimseohyun
  image: 01.jpg
  say-hello: Hello, I’m <strong>kim seohyun</strong>
  bio: Designs, talks, and writes about <strong>web</strong>, <strong>ethics</strong>, <strong>privacy</strong>, and dev. I share design tutorials, free resources and inspiration. Loves <a href="#">music</a> & riding his bicycle.


#-------------------------------

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown

