<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Kim Seohyun Portfolio</title>
  <style>
    /* 전체 페이지 스타일 */
    body, html {
      margin: 0;
      padding: 0;
      height: 100%;
      font-family: Arial, sans-serif;
      display: flex;
      justify-content: center;
      align-items: center;
      background-color: #f4f4f4;
    }

    /* 타자 치는 효과를 위한 스타일 */
    .typing-container {
      font-size: 2em;
      color: #333;
      font-weight: bold;
      white-space: nowrap; /* 텍스트가 한 줄로 유지되도록 설정 */
      overflow: hidden; /* 화면 밖으로 나가지 않게 설정 */
    }

    /* 각 글자마다 타자 효과를 부여 */
    .typing-container span {
      display: inline-block;
      opacity: 0;  /* 처음에는 보이지 않게 설정 */
      animation: typing 3s steps(20) 1s forwards;  /* 타자 애니메이션 */
    }

    /* 글자 하나씩 타자 효과 */
    .typing-container span:nth-child(1) { animation-delay: 0s; }
    .typing-container span:nth-child(2) { animation-delay: 0.2s; }
    .typing-container span:nth-child(3) { animation-delay: 0.4s; }
    .typing-container span:nth-child(4) { animation-delay: 0.6s; }
    .typing-container span:nth-child(5) { animation-delay: 0.8s; }
    .typing-container span:nth-child(6) { animation-delay: 1s; }
    .typing-container span:nth-child(7) { animation-delay: 1.2s; }
    .typing-container span:nth-child(8) { animation-delay: 1.4s; }
    .typing-container span:nth-child(9) { animation-delay: 1.6s; }
    .typing-container span:nth-child(10) { animation-delay: 1.8s; }
    .typing-container span:nth-child(11) { animation-delay: 2s; }
    .typing-container span:nth-child(12) { animation-delay: 2.2s; }
    .typing-container span:nth-child(13) { animation-delay: 2.4s; }
    .typing-container span:nth-child(14) { animation-delay: 2.6s; }
    .typing-container span:nth-child(15) { animation-delay: 2.8s; }
    .typing-container span:nth-child(16) { animation-delay: 3s; }
    .typing-container span:nth-child(17) { animation-delay: 3.2s; }
    .typing-container span:nth-child(18) { animation-delay: 3.4s; }
    .typing-container span:nth-child(19) { animation-delay: 3.6s; }
    .typing-container span:nth-child(20) { animation-delay: 3.8s; }

    /* 타자 효과 애니메이션 */
    @keyframes typing {
      from {
        width: 0;
        opacity: 1;
      }
      to {
        width: 100%;
        opacity: 1;
      }
    }
  </style>
</head>
<body>

  <div class="typing-container">
    <!-- 글자 하나씩 나열하기 -->
    <span>K</span>
    <span>i</span>
    <span>m</span>
    <span>&nbsp;</span>
    <span>S</span>
    <span>e</span>
    <span>o</span>
    <span>h</span>
    <span>y</span>
    <span>u</span>
    <span>n</span>
    <span>&nbsp;</span>
    <span>P</span>
    <span>o</span>
    <span>r</span>
    <span>t</span>
    <span>f</span>
    <span>o</span>
    <span>l</span>
    <span>i</span>
    <span>o</span>
  </div>

</body>
</html>

