#-------------------------------
# General Site Settings
title: PORTFOLIO
description: Zolan is modern minimal theme for Jekyll


#-------------------------------
# Author Settings
author:
  name: Kimseohyun
  image: 01.jpg
  say-hello: <strong>kim seohyun portfolio</strong>


disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown
