<!-- General Site Settings -->
<meta name="title" content="SEOHYUN PORTFOLIO">
<meta name="description" content="Zolan is modern minimal theme for Jekyll">

<!-- Author Settings -->
<div class="author">
  <h2>Kimseohyun</h2>
  <img src="01.jpg" alt="Kimseohyun" />
  <p>Hello, I’m <strong>kim seohyun</strong></p>
  <p>Designs, talks, and writes about <strong>web</strong>, <strong>ethics</strong>, <strong>privacy</strong>, and dev. I share design tutorials, free resources, and inspiration. Loves <a href="#">music</a> & riding his bicycle.</p>
</div>

<!-- Comment Section (Disqus) -->
<div class="comments">
  <h3>Comments</h3>
  <div id="disqus_thread"></div>
  <script>
    var disqus_config = function () {
      this.page.url = window.location.href;  // Page URL
      this.page.identifier = 'mr-brown'; // Disqus shortname
    };
    
    (function() {  // Load Disqus
      var s = document.createElement('script');
      s.src = 'https://mr-brown.disqus.com/embed.js';
      s.setAttribute('data-timestamp', +new Date());
      (document.head || document.body).appendChild(s);
    })();
  </script>
</div>


