<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Kim Seohyun Portfolio</title>
  <style>

    body, html {
      margin: 0;
      padding: 0;
      height: 100%;
      font-family: Arial, sans-serif;
      display: flex;
      justify-content: center;
      align-items: center;
      background-color: #f4f4f4;
    }

    .content {
      font-size: 2em;
      color: #333;
      font-weight: bold;
      white-space: nowrap;
      animation: slideRightLeft 3s ease-in-out infinite;
    }


    @keyframes slideRightLeft {
      0% {
        transform: translateX(0);
      }
      50% {
        transform: translateX(100px);
      }
      100% {
        transform: translateX(0); 
      }
    }
  </style>
</head>
<body>

  <div class="content">
    <p>Kim Seohyun Portfolio</p>
  </div>

</body>
</html>
